### ISSUE TITLE
Extra landscaping Suface should be intgrated into this, Or released on PDX mods

### ISSUE THREAD

**Issue by ryjayt** [AlphaGaming7780/ExtraLandscapingTools#1]
Its such a good mod and im missing it

**Comment by AlphaGaming7780** [comment]
I'm working on it but it's not going to be in this mod.

It's going to be in a new mod with all the unreleased features of ELT 3.0.

**Comment by AlphaGaming7780** [comment]
Done in EDT → https://mods.paradoxplaza.com/mods/80528/Windows
