### ISSUE TITLE
mod does not appear in the game

### ISSUE THREAD

**Issue by LukNasc** [AlphaGaming7780/ExtraLandscapingTools#6]
Mod is installed
![image](https://github.com/AlphaGaming7780/ExtraLandscapingTools/assets/26725196/8818fb41-2711-4219-b6db-36a246dc943a)

but not appear in the game
![image](https://github.com/AlphaGaming7780/ExtraLandscapingTools/assets/26725196/733ae22e-7687-4f60-8535-8d0e993c31a8)

**Comment by AlphaGaming7780** [comment]
Check in the landscaping menu, you should see the brush selector and brush angle parameters for the landscaping tools.

**Comment by asciant** [comment]
I believe he means that the mod that used to appear in the Landscaping settings has disappeared.

I had the same, working fine until today, I assume related to the updates you pushed earlier today.

![image](https://github.com/AlphaGaming7780/ExtraLandscapingTools/assets/21677/a6fca5d9-0554-4050-8109-c7f6cae57927)

**Comment by AlphaGaming7780** [comment]
I didn't update the mod today.
The last update is the 26 March.
I think the issue come from another mod, that are incompatible with my mod.
But when I try to install the mods people have, everything work fine.
So I'm a bit lost, nothing in the log player send me (if they send me their logs)

**Comment by asciant** [comment]
Weird ok, I deactivated and reactivated both yours and extra lib, restarted game and your mod started working again. So not too sure unfortunately.

**Comment by LukNasc** [comment]
How can i use surface tools? like extends college surface, im using wrong mod?

**Comment by asciant** [comment]
@AlphaGaming7780 I uninstalled all mods, except ELT and its dependencies. The mod still occasionally fails to load, and does not display the tools as per my snippet in my [previous post](https://github.com/AlphaGaming7780/ExtraLandscapingTools/issues/6#issuecomment-2056181370)

**Comment by AlphaGaming7780** [comment]
> How can i use surface tools? like extends college surface, im using wrong mod?

For now, you need to use the dev mod, the mod showing the surfaces in the UI isn't published yet, but it's coming soon.

**Comment by AlphaGaming7780** [comment]
> @AlphaGaming7780 I uninstalled all mods, except ELT and its dependencies. The mod still occasionally fails to load, and does not display the tools as per my snippet in my [previous post](https://github.com/AlphaGaming7780/ExtraLandscapingTools/issues/6#issuecomment-2056181370)

Yeah, C:S 2 doesn't load few mods sometimes for some reason.

**Comment by LukNasc** [comment]
Apparently the game has an inconsistency when loading mods, as sometimes all my installed mods don't appear when I start the game. I believe it to start correctly with all mods installed. In the Launcher you need to choose the "Play" option to go to the home menu and not the "continue" option, this option may not load the mods correctly.
